Export to the real XLS
osalabs/osafw-asp.net-core pull request #127
Opened 2024-10-20 16:56 UTC by KrNikita

- Code migrated from VB from the different project
- I made it basic but a little bit more work is needed before you can review it.

2024-11-04 13:23 UTC, KrNikita commented
The code moved to the ConvUtils.

2025-01-06 21:40 UTC, osalabs requested changes

2025-01-06 21:40 UTC, osalabs commented on osafw-app/App_Code/fw/ConvUtils.cs
> +    public static Dictionary<string, int> GetMaxCharacterWidth(ArrayList rows, List<string> headers)
this seems should be a private method?

2025-01-06 21:40 UTC, osalabs commented on osafw-app/App_Code/fw/ConvUtils.cs
> +    public static DocumentFormat.OpenXml.Spreadsheet.Columns AutoSizeCells(ArrayList rows, List<string> headers)
this also should be a private method.

2025-01-06 21:40 UTC, osalabs commented on osafw-app/App_Code/fw/ConvUtils.cs
> +    public static Stylesheet GetStylesheet()
make private too?
Also, maybe name it more specifically `GetExcelStylesheet`

2025-01-06 21:40 UTC, osalabs commented on osafw-app/App_Code/fw/ConvUtils.cs
> +        var _Fonts = new DocumentFormat.OpenXml.Spreadsheet.Fonts();
also, you already `using DocumentFormat.OpenXml.Spreadsheet`, so can simplify everything below?

2025-01-06 21:40 UTC, osalabs commented on osafw-app/App_Code/fw/ConvUtils.cs
> +    public static string parsePageNativeExcel(FW fw, string xls_export_headers, string xls_export_fields, ArrayList rows, string out_filename = "")
make output similar to other parsePage methods - depending on out_filename.
I.e. if it's empty - output to browser with proper headers

2025-01-06 21:40 UTC, osalabs commented on osafw-app/App_Code/fw/FwReports.cs
> +using Microsoft.AspNetCore.Http;
I don't want all this stuff here. FwReports should not know about these. Do everything in `ConvUtils`

2025-01-06 21:40 UTC, osalabs commented on osafw-app/App_Code/fw/FwReports.cs
> +                    fw.fileResponse(filepath, report_code + ".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "attachment");
move this under `parsePageNativeExcel` - see how it's done in other methods

2025-01-06 21:40 UTC, osalabs commented on osafw-app/App_Data/template/admin/reports/common/btn_download.html
How about list screens export? On list screens we also have Export to .xlsx. Make sense to change export to native xls too?

2025-05-19 19:50 UTC, merged